// Mocks generated by Mockito 5.3.2 from annotations
// in recipe_search_app/test/recipe_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_search_app/data/models/recipe_details_model.dart' as _i3;
import 'package:recipe_search_app/data/models/recipe_model.dart' as _i2;

import 'recipe_bloc_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipeModel_0 extends _i1.SmartFake implements _i2.RecipeModel {
  _FakeRecipeModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecipeDetailsModel_1 extends _i1.SmartFake
    implements _i3.RecipeDetailsModel {
  _FakeRecipeDetailsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockApiRepository extends _i1.Mock implements _i4.MockApiRepository {
  MockMockApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RecipeModel> searchRecipes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecipes,
          [query],
        ),
        returnValue: _i5.Future<_i2.RecipeModel>.value(_FakeRecipeModel_0(
          this,
          Invocation.method(
            #searchRecipes,
            [query],
          ),
        )),
      ) as _i5.Future<_i2.RecipeModel>);
  @override
  _i5.Future<_i3.RecipeDetailsModel> getRecipeDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeDetails,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.RecipeDetailsModel>.value(_FakeRecipeDetailsModel_1(
          this,
          Invocation.method(
            #getRecipeDetails,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.RecipeDetailsModel>);
}
